name: Repository Dispatch
description: Create a repository dispatch event
inputs:
  token:
    description: A GitHub Personal Access Token - get it from `1Password > Github - ubiobot`
    required: true
  owner:
    description: The owner of the repository to send the dispatch event to (eg `universalbasket`)
    required: true
  repository:
    description: The name of the repository to send the dispatch event to (eg `my-repo`)
    required: true
  event:
    description: The event type
    required: true
  payload:
    description: JSON payload with data that your target action or worklow may use
    default: "{}"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.owner }}
    - ${{ inputs.repository }}
    - ${{ inputs.event }}
    - ${{ inputs.payload }}
branding:
  icon: target
  color: gray-dark
