name: Pull Request
description: Create a pull request
inputs:
  token:
    description: A GitHub Personal Access Token
    required: true
  message:
    description: The commit message
    required: true
  files:
    description: |
      Comma-separated list of files to commit and their location.
      Example: pull-request/README.md,pull-request/src/main.go
    required: true
  owner:
    description: The owner of the repo to create a PR on (eg `ubio`)
    required: true
  repository:
    description: The name of the repo to create a PR on (eg `my-repo`)
    required: true
  title:
    description: The PR title
    required: true
  body:
    description: The body of the PR
    required: false
  head:
    description: Name of branch where changes are implemented
    required: true
  base:
    description: Name of branch where changes should be pulled into
    required: true
  draft:
    description: Whether the PR is in draft status
    required: false
    default: false
  maintainer_can_modify:
    description: Whether repo maintainers can modify the PR
    required: false
    default: true
  merge:
    description: Whether to auto-merge the PR once it's mergeable
    required: false
    default: false
  assignees:
    description: Add assignees to the PR
    required: false
    default: ""
output:
  pr:
    description: A link to the PR
output:
  merged:
    description: Whether or not the generated PR was merged
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.message }}
    - ${{ inputs.files }}
    - ${{ inputs.owner }}
    - ${{ inputs.repository }}
    - ${{ inputs.title }}
    - ${{ inputs.body }}
    - ${{ inputs.head }}
    - ${{ inputs.base }}
    - ${{ inputs.draft }}
    - ${{ inputs.maintainer_can_modify }}
    - ${{ inputs.merge }}
    - ${{ inputs.assignees }}
branding:
  icon: target
  color: gray-dark
