on:
  workflow_call:
    inputs:
      gh_user:
        required: true
        type: string
      gh_repo:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      env_name:
        required: true
        type: string
      app_path:
        required: true
        type: string
      auto_merge:
        required: true
        type: boolean
    secrets:
      ACCESS_TOKEN:
        required: true
jobs:
  dispatch:
    name: Dispatch repo event
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract tag as env var
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Notify repo
        uses: docker://automationcloud/repository-dispatch:latest
        with:
          owner: ${{ inputs.gh_user }}
          repository: ${{ inputs.gh_repo }}
          token: ${{ secrets.ACCESS_TOKEN }}
          event: cd-deploy
          payload: |-
            {
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "tag": "${{ env.RELEASE_VERSION }}",
              "image_name": "${{ inputs.image_name }}",
              "image_tag": "${{ env.RELEASE_VERSION }}",
              "env_name": "${{ inputs.env_name }}",
              "app_path": "${{ inputs.app_path }}",
              "auto_merge": "${{ inputs.auto_merge }}"
            }
