on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      env_name:
        required: true
        type: string
      app_path:
        required: true
        type: string
      auto_merge:
        required: true
        type: boolean
    secrets:
      ACCESS_TOKEN:
        required: true
jobs:
  create_pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update kustomization.yaml
        uses: mikefarah/yq@3.3.0
        with:
          cmd: yq w -i ./${{ inputs.app_path }}/overlays/${{ inputs.env_name }}/kustomization.yaml "images.(name==${{ inputs.image_name }}).newTag" ${{ inputs.image_tag }}

      - name: Build
        uses: docker://automationcloud/kustomize:latest
        with:
          kustomize_build_dir: "./${{ inputs.app_path }}/overlays/${{ inputs.env_name }}"
          kustomize_output_file: "./${{ inputs.app_path }}/manifests/${{ inputs.env_name }}/install.yaml"
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Create the PR
        uses: docker://automationcloud/pull-request:latest
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          owner: ubio
          repository: k8s
          message: Update image
          files: ${{ inputs.app_path }}/overlays/${{ inputs.env_name }}/kustomization.yaml,${{ inputs.app_path }}/manifests/${{ inputs.env_name }}/install.yaml
          title: Update ${{ inputs.image_name }} to ${{ inputs.image_tag }} (${{ inputs.env_name }})
          body: Automated PR for ${{ inputs.image_name }}:${{ inputs.image_tag }} (${{ inputs.env_name }})
          head: ${{ inputs.image_name }}-${{ github.run_id }}-${{ inputs.env_name }}
          base: master
          draft: false
          maintainer_can_modify: true
          merge: ${{ inputs.auto_merge }}
