on:
  workflow_call:
    inputs:
      go_version:
        default: "1.17"
        required: false
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Go
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go_version }}
      - name: Grant private modules access
        run: |
          git config --global url."https://ubiobot:${{ secrets.ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Bootstrap
        run: script/bootstrap
      - name: Vendor
        run: script/vendor
      - name: Build
        run: script/build
      - name: Test
        run: script/test
