name: Docker Build

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      REGISTRY_SECRET:
        required: true

jobs:
  build_image:
    name: Builds a docker image and pushes to the registry
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag as an ENV var
        run: |
          ref="${{ github.ref }}"
          echo "TAG=${ref/refs\/tags\//}" >> $GITHUB_ENV
      - name: Login to the Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ env.REGISTRY_SECRET }}
      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ inputs.image }}:${{ env.TAG }}
          push: true
