name: Build image

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      REGISTRY_SECRET:
        required: true

jobs:
  build_image:
    name: Builds a docker image and pushes to the registry
    runs-on: ubuntu-latest
    steps:
      - name: Login to the Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ env.REGISTRY_SECRET }}
      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ inputs.image }}:${{ inputs.tag }}
          push: true
