name: Docker Build

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      ref:
        required: true
        type: string
      name:
        required: true
        type: string
    secrets:
      REGISTRY_SECRET:
        required: true
      SLACK_CHANNEL:
        required: true
      SLACK_TOKEN:
        required: true

jobs:
  build_image:
    name: Builds a docker image and pushes to the registry
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag as an ENV var
        run: |
          ref="${{ github.ref }}"
          echo "TAG=${ref/refs\/tags\//}" >> $GITHUB_ENV
      - name: Login to the Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.REGISTRY_SECRET }}
      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ inputs.image }}:${{ env.TAG }}
          push: true
      - name: Notify Slack
        if: ${{ success() }}
        uses: docker://automationcloud/rsslack:latest
        with:
          channel: ${{ inputs.slack_channel }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          message: ":package: *${{ inputs.name }}* has been built and pushed to `${{ inputs.image }}:${{ env.TAG }}`"
