name: release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  release-cert-checker:
    runs-on: ubuntu-latest
    name: release-cert-checker
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: release cert-checker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ubio/cert-checker
          path: ./cert-checker
          tag_with_sha: true

  release-cert-notifier:
    runs-on: ubuntu-latest
    name: release-cert-notifier
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: release cert-notifier
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ubio/cert-notifier
          path: ./cert-notifier
          tag_with_sha: true

  release-pull-request:
    runs-on: ubuntu-latest
    name: release-pull-request
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: release pull-request
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ubio/pull-request
          path: ./pull-request
          tag_with_sha: true

  release-repository-dispatch:
    runs-on: ubuntu-latest
    name: release-repository-dispatch
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: release repository-dispatch
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ubio/repository-dispatch
          path: ./repository-dispatch
          tag_with_sha: true

  release-rsslack:
    runs-on: ubuntu-latest
    name: release-rsslack
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: release rsslack
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ubio/rsslack
          path: ./rsslack
          tag_with_sha: true